#!/bin/bash
# Assisted by watsonx Code Assistant 
# Code generated by WCA@IBM in this programming language is not approved for use in IBM product development.
set -euo pipefail

# where are the fitlet fonts?
path="$(figlet -I 2)"

for file in ${path}/*.?lf; do
    filename="${file%.*}"
    fontname="${filename##*/}"
    message="This is ${fontname}"
    printf "${message}\n"
    figlet -t -f "${fontname}" "${message}"
done
