name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  LLAMACPP_VER: b3472

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s) --tag thebiss/llama-cpp-mkl:${LLAMACPP_VER} --tag thebiss/llama-cpp-mkl:latest --build-arg LLAMACPP_VERSION_TAG=${LLAMACPP_VER}
